# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    download_directory: '../public/'
    admin_email: admin@email.bg

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        #GLOBAL PARAM WHICH IS IN EVERY SERVICE IN THIS YAML FILE
        bind:
            $globalParam: 'global param to be used by all services defined in this file'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    App\Services\MyService:
        arguments:
            $service: '@App\Services\MySecondService'
            # $param: 'some parameter'
            # $adminEmail: '%admin_email%'
            # $second_service: '@App\Services\MySecondService'
    App\Services\MySecondService:
        lazy: true
    # App\Controller\DefaultController:
    #     bind:
    #         $logger: '@monolog.logger.doctrine'
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
